
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://www.ruler.mysql.com:3306/flow_db?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: ogdzgT+Ot36r9PXiHE9fQyv+utQJSe4Dzg8HV6VnCw5gKX+ugbqXDgelkL7lpIMJxyNfBEkX410Z6wP7w/70LA==
    # 使用Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKJNBBHgjNGmxN6l9lgfX6SVrGAe8S5m2cIVWAu4zLtRxIULudjLBYOJEjiheTF6fBr7x9nd/otJb6XLyh2hT0ECAwEAAQ==
      filters: config,stat,wall,log4j
      connectionProperties: config.decrypt=true;config.decrypt.key=${spring.datasource.druid.publickey}
      web-stat-filter:
        enabled: true
        url-pattern: "/*" #添加过滤规则
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #添加不需要忽略的格式信息
        session-stat-enable: true
        session-stat-max-count: 1000
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        login-username: admin
        login-password: admin
        allow: #白名单
        deny: #黑名单
        reset-enable: false
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

mybatis:
  # Mybatis配置Mapper路径
  mapper-locations: classpath:mapper/*.xml
  # Mybatis配置Model类对应
  type-aliases-package: com.litsoft.flowable.bussiness.*.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  params: count=countSql
  # 指定分页插件使用哪种方言
  helper-dialect: mysql
  # 分页合理化参数 pageNum<=0时会查询第一页 pageNum>pages(超过总数时) 会查询最后一页
  reasonable: 'true'
  support-methods-arguments: 'true'

mapper:
  # 通用Mapper的insertSelective和updateByPrimaryKeySelective中是否判断字符串类型!=''
  not-empty: true

logging:
  level.root: info
  level.com.haiyang: debug
  path: logs/
  file: flowable-test.log